name: Build and Deploy Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: reminr-dev
  NAME: reminr-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_DEV }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Create Env file
        run: |
          echo "${{ secrets.DEV_ENV }}" | base64 --decode > .env.yml
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Push Docker Image
        run: |
          gcloud builds submit . --config=cloudbuild.yml \
            --substitutions=_IMAGE=${{ env.NAME }},_FILE_PATH=Dockerfile
