name: Migration(Prod)

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  PROJECT_ID: reminr-prod
  CONNECTION_NAME: reminr-prod:us-central1:reminr-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DB_SA_PROD }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Download SQL Auth Proxy
        run: 'wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud-sql-proxy'
      - name: Make the Cloud SQL Auth proxy executable
        run: 'chmod +x cloud-sql-proxy'
      - name: Start the Cloud SQL proxy and run migrations
        run: './cloud-sql-proxy -instances=${{ env.CONNECTION_NAME }}=tcp:5432 & npx prisma migrate deploy'
        env:
          DATABASE_URL: ${{ secrets.DB_URL_PROD }}
          DIRECT_URL: ${{ secrets.DB_URL_PROD }}
          INSTANCE_HOST: localhost
          DB_PORT: 5432
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASSWORD: ${{ secrets.DB_PASS_PROD }}
