name: Migration(Dev) CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'prisma/**'
      - '.github/workflows/migration.dev.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run migrations
        run: 'npx prisma migrate deploy'
        env:
          DATABASE_URL: ${{ secrets.DEV_DB_URL }}
