name: Build and Deploy (Production)

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  PROJECT_ID: reminr-prod
  NAME: reminr-api
  CONNECTION_NAME: reminr-prod:us-central1:reminr-prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_PROD }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Create Env file
        run: |
          echo "${{ secrets.PROD_ENV }}" | base64 --decode > .env.yml
      - name: Configure Service Account
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: 'serviceAccountKey.json'
          json: ${{ secrets.FB_SA_PROD }}
          dir: 'src/config/'
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Push Docker Image
        run: |
          gcloud builds submit . --config=cloudbuild.yml \
            --substitutions=_IMAGE=${{ env.NAME }},_FILE_PATH=Dockerfile

  deploy-schedular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Create Env file
        run: |
          echo "${{ secrets.FUNCTIONS_PROD_ENV }}" > .env
      - name: Configure Service Account
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: 'serviceAccountKey.json'
          json: ${{ secrets.FB_SA_PROD }}
          dir: 'src/config/'
      - name: Create .firebaserc
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: '.firebaserc'
          json: ${{ secrets.PROD_FIREBASERC }}
          dir: './'
      - name: Deploy functions
        uses: w9jds/firebase-action@v13.3.0
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_PROD }}
