name: Build and Deploy (Production)

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  PROJECT_ID: reminr-prod
  NAME: reminr-api
  CONNECTION_NAME: reminr-prod:us-central1:reminr-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_PROD }}
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Create Env file
        run: |
          echo "${{ secrets.PROD_ENV }}" | base64 --decode > .env.yml
      - name: Configure Service Account
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: 'serviceAccountKey.json'
          json: ${{ secrets.FB_SA_PROD }}
          dir: 'src/config/'
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Push Docker Image
        run: |
          gcloud builds submit . --config=cloudbuild.yml \
            --substitutions=_IMAGE=${{ env.NAME }},_FILE_PATH=Dockerfile
      - name: Add Cloud Sql Instance IP
        run: |
          gcloud run services update ${{ env.NAME }} --add-cloudsql-instances ${{ env.CONNECTION_NAME }}
